export type AgentRole = {
  id: string;
  name: string;
  specialty: string;
};

export type AgentStep = {
  agentId: string;
  title: string;
  detail: string;
  status: "queued" | "running" | "done";
};

export type AgentRunResult = {
  mode: "demo" | "live";
  steps: AgentStep[];
  output: {
    headline: string;
    summary: string;
    artifacts: Array<{ label: string; content: string }>;
    previewHtml?: string;
    imagePrompt?: string;
    videoBrief?: string;
  };
  apiNote: string;
};

export const TASKS = {
  web: {
    slug: "web",
    title: "AI Web Page Creation",
    blurb: "Conversation-first landing pages with Brand DNA baked in.",
    href: "/app/web",
    agents: [
      { id: "strategist", name: "Brand Strategist", specialty: "Positioning & offer" },
      { id: "copy", name: "Copywriter", specialty: "Headlines & sections" },
      { id: "layout", name: "Layout Architect", specialty: "Structure & CTA flow" },
    ] satisfies AgentRole[],
  },
  image: {
    slug: "image",
    title: "AI Image Generation",
    blurb: "Campaign visuals, mood boards, and social-ready stills.",
    href: "/app/image",
    agents: [
      { id: "art", name: "Art Director", specialty: "Visual direction" },
      { id: "prompt", name: "Prompt Engineer", specialty: "Generation prompts" },
      { id: "style", name: "Style Critic", specialty: "Brand consistency" },
    ] satisfies AgentRole[],
  },
  video: {
    slug: "video",
    title: "AI Video Creation",
    blurb: "Scripts, shot lists, and motion briefs ready to produce.",
    href: "/app/video",
    agents: [
      { id: "script", name: "Scriptwriter", specialty: "Hooks & narration" },
      { id: "shots", name: "Shot Planner", specialty: "Scenes & pacing" },
      { id: "motion", name: "Motion Director", specialty: "Style & delivery" },
    ] satisfies AgentRole[],
  },
} as const;

export type TaskKey = keyof typeof TASKS;

export function runAgents(task: TaskKey, brief: string): AgentRunResult {
  const subject = brief.trim() || "a new product launch";
  const pack = TASKS[task];
  const hasOpenAI = Boolean(process.env.OPENAI_API_KEY);
  const hasImage = Boolean(process.env.OPENAI_API_KEY || process.env.REPLICATE_API_TOKEN);
  const hasVideo = Boolean(process.env.RUNWAY_API_KEY || process.env.REPLICATE_API_TOKEN);

  const steps: AgentStep[] = pack.agents.map((agent, index) => ({
    agentId: agent.id,
    title: `${agent.name} · ${agent.specialty}`,
    detail:
      index === 0
        ? `Framed the brief around “${subject}”.`
        : index === 1
          ? `Drafted core assets for ${pack.title.toLowerCase()}.`
          : `Checked consistency against Brand DNA and channel fit.`,
    status: "done",
  }));

  if (task === "web") {
    return {
      mode: hasOpenAI ? "live" : "demo",
      steps,
      output: {
        headline: subject,
        summary: `Three agents drafted a conversational website starter for “${subject}”.`,
        artifacts: [
          { label: "Hero", content: `${subject} — built in conversation, shipped with confidence.` },
          { label: "CTA", content: "Start free · Book a demo · See examples" },
          {
            label: "Sections",
            content: "Problem → Solution → Proof → Features → FAQ → Close",
          },
        ],
        previewHtml: `<section style="font-family:Georgia,serif;padding:2rem;background:linear-gradient(160deg,#f7b6c8,#f3d9a4);color:#2b2420"><p style="letter-spacing:.16em;text-transform:uppercase;font-size:.7rem">Pixie Dust · Web Agent</p><h1 style="font-size:2rem;margin:.5rem 0 1rem">${subject}</h1><p>Create. Launch. Grow. — generated by coordinated AI agents.</p><a style="display:inline-block;margin-top:1rem;padding:.75rem 1.2rem;border-radius:999px;background:#2b2420;color:#fff8f4;text-decoration:none">Get started</a></section>`,
      },
      apiNote: hasOpenAI
        ? "OPENAI_API_KEY detected — wire live LLM rewrite in a follow-up."
        : "Demo agents active. Optional: set OPENAI_API_KEY for live copy generation.",
    };
  }

  if (task === "image") {
    const imagePrompt = `Editorial campaign still for “${subject}”, soft bakery light, rose sugar and champagne gold palette, shallow depth of field, no text overlay, premium lifestyle product photography`;
    return {
      mode: hasImage ? "live" : "demo",
      steps,
      output: {
        headline: `Visual system for ${subject}`,
        summary: "Art Director + Prompt Engineer + Style Critic produced a generation-ready brief.",
        artifacts: [
          { label: "Primary prompt", content: imagePrompt },
          { label: "Formats", content: "1:1 feed · 4:5 story · 16:9 hero" },
          { label: "Negative", content: "No watermarks, no cluttered backgrounds, no distorted hands" },
        ],
        imagePrompt,
      },
      apiNote: hasImage
        ? "Image provider key detected — connect generation endpoint next."
        : "Demo agents active. Real pixels need OPENAI_API_KEY (DALL·E) or REPLICATE_API_TOKEN.",
    };
  }

  const videoBrief = `15s opener for “${subject}”: hook (0–3s), product moment (3–10s), CTA (10–15s). Warm rose/gold grade, handheld intimacy, end card Create. Launch. Grow.`;
  return {
    mode: hasVideo ? "live" : "demo",
    steps,
    output: {
      headline: `Motion brief for ${subject}`,
      summary: "Scriptwriter + Shot Planner + Motion Director aligned a launch clip plan.",
      artifacts: [
        { label: "Hook", content: `What if ${subject} marketed itself overnight?` },
        { label: "Shot list", content: "1) Detail macro 2) Human reaction 3) UI/product 4) Logo lockup" },
        { label: "Delivery", content: "Vertical 9:16 first, crop to 1:1 and 16:9" },
      ],
      videoBrief,
    },
    apiNote: hasVideo
      ? "Video provider key detected — connect render pipeline next."
      : "Demo agents active. Real video needs RUNWAY_API_KEY or REPLICATE_API_TOKEN.",
  };
}
